# Generated by Django 5.1.4 on 2024-12-29 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0007_remove_match_unique_match_number_match_round_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tournaments_won",
                to="tournament.player",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="tournament.tournament",
            ),
        ),
    ]
