# Generated by Django 5.1.4 on 2024-12-24 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0005_alter_match_player1_alter_match_player2"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="is_over",
            field=models.BooleanField(default=False),
        ),
    ]
