services:
  web:
    # todo: ディレクトリ名とサービス名をappに変更
    build: ./web
    container_name: web
    command: /bin/sh -c "web/entrypoint.sh"
    volumes:
      - .:/usr/src/app
    env_file: .env
    environment:
      - DEBUG=True
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: ./web/requirements.txt

  db:
    image: postgres
    container_name: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file: .env
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "dbuser", "-d", "djangodb" ]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "localhost", "ping" ]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s

include:
  - ./blockchain/blockchain.yml
