# https://docs.docker.com/compose/how-tos/production/
# https://docs.docker.com/compose/how-tos/multiple-compose-files/merge/
# https://docs.docker.com/reference/compose-file/merge/

services:
  account:
    volumes: !reset []
    entrypoint: !override "/usr/src/app/entrypoint.sh"
    environment: !override
      - ENVIRONMENT=production
    development: !reset []
    ports: !reset []

  gameplay:
    volumes: !reset []
    entrypoint: !override "/usr/src/app/entrypoint.sh"
    environment: !override
      - ENVIRONMENT=production
    development: !reset []
    ports: !reset []

  tournament:
    volumes: !reset []
    entrypoint: !override "/usr/src/app/entrypoint.sh"
    environment: !override
      - ENVIRONMENT=production
    development: !reset []
    ports: !reset []

  db:
    volumes: !override
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  frontend:
    environment: !override
      - ACCOUNT_HOST=https://localhost:8443/42pong.api/account
      - GAMEPLAY_HOST=https://localhost:8443/42pong.api/gameplay
      - GAMEPLAY_WS_HOST=wss://localhost:8443/gameplay.ws
      - TOURNAMENT_HOST=https://localhost:8443/42pong.api/tournament
    ports: !reset []

  web:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: web
    ports:
      - "8443:443"
    depends_on:
      account:
        condition: service_healthy
      gameplay:
        condition: service_healthy
      frontend:
        condition: service_healthy
    command: ["nginx", "-g", "daemon off;"]

include:
  - ./elk/elk-services.yml
