services:
  web:
    # todo: ディレクトリ名とサービス名をappに変更
    build: ./web
    container_name: web
    command: /bin/sh -c "web/entrypoint.sh"
    volumes:
      - .:/usr/src/app
    env_file: .env
    environment:
      - DEBUG=True
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    container_name: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file: .env
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "dbuser", "-d", "djangodb" ]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
  
  frontend:
    image: node:latest
    container_name: frontend
    working_dir: /usr/src/frontend
    command: /bin/sh -c "npm install && npm run server"
    volumes:
      - ./frontend:/usr/src/frontend
    ports:
      - "3000:3000"
    # depends_on:

  websocket:
    build: ./web
    container_name: websocket
    command: daphne -b 0.0.0.0 -p 4242 core.asgi:application
    volumes:
      - ./web:/usr/src/app
    env_file: .env
    ports:
      - "4242:4242"
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "localhost", "ping" ]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s