services:
  app:
    # todo: ディレクトリ名もappに変更
    build: ./web
    container_name: app
    command: /bin/sh -c "web/entrypoint.sh"
    volumes:
      - .:/usr/src/app
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy

  db:
    image: postgres
    container_name: db
    volumes:
      - ./data/db_prod:/var/lib/postgresql/data
    env_file: .env
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "dbuser", "-d", "djangodb" ]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s

  web:
    image: nginx
    container_name: web
    volumes:
      # - ./web/static:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "localhost", "ping" ]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s

include:
  - ./elk/elk-services.yml
