services:
  web:
    # todo: ディレクトリ名とサービス名をappに変更
    build: ./web
    container_name: web
    command:
      - /bin/sh
      - -c
      - |
        python3 web/manage.py makemigrations &&
        python3 web/manage.py migrate &&
        python3 web/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    container_name: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file: .env
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "dbuser", "-d", "djangodb" ]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
