# Generated by Django 5.1.4 on 2024-12-21 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0004_match_player1_match_player1_score_match_player2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="player1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_as_player1",
                to="tournament.player",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="player2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_as_player2",
                to="tournament.player",
            ),
        ),
    ]
