# Generated by Django 5.1.4 on 2024-12-26 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0006_tournament_is_over"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="match",
            name="unique_match_number",
        ),
        migrations.AddField(
            model_name="match",
            name="round",
            field=models.IntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name="match",
            constraint=models.UniqueConstraint(
                fields=("tournament", "round", "match_number"),
                name="unique_round_match_number",
            ),
        ),
    ]
