# Generated by Django 5.1.4 on 2024-12-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("websocket", "0002_gamestate_action_alter_gamestate_game_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamestate",
            name="action",
        ),
        migrations.RemoveField(
            model_name="gamestate",
            name="game_state",
        ),
        migrations.AddField(
            model_name="gamestate",
            name="ball_x",
            field=models.FloatField(default=500),
        ),
        migrations.AddField(
            model_name="gamestate",
            name="ball_y",
            field=models.FloatField(default=300),
        ),
        migrations.AddField(
            model_name="gamestate",
            name="l_player",
            field=models.FloatField(default=240),
        ),
        migrations.AddField(
            model_name="gamestate",
            name="l_score",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="gamestate",
            name="r_player",
            field=models.FloatField(default=240),
        ),
        migrations.AddField(
            model_name="gamestate",
            name="r_score",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="gamestate",
            name="state",
            field=models.CharField(default="waiting", max_length=20),
        ),
        migrations.AlterField(
            model_name="gamestate",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
