services:
  ganache:
    image: trufflesuite/ganache:latest
    platform: linux/amd64
    container_name: ganache
    ports:
      - "8545:8545"
    volumes:
      - ganache_data:/data
    environment:
      MNEMONIC: "${MNEMONIC}"
    command:
      - --host
      - "0.0.0.0"
      - --mnemonic
      - "${MNEMONIC}"

  truffle:
    build:
      context: ./truffle
      dockerfile: Dockerfile
    container_name: truffle
    depends_on:
      - ganache
    command:
      ["sh", "-c", "truffle compile && truffle migrate --network development --reset && truffle test"]
    volumes:
      - ./truffle:/app
      - /app/node_modules

volumes:
  ganache_data:
    driver: local
