openapi: 3.0.0
info:
  title: Authentication API
  version: 1.0.0
  description: |
    PongゲームのAcount/OPTを管理するためのREST API
    - User Login, Signup
    - OPTのセットアップとトークン検証

servers:
  - url: http://localhost:3000
    description: 開発用サーバー

paths:
  /api/login:
    post:
      tags:
        - authentication
      summary: ユーザーログイン
      responses:
        "200":
          description: ログイン成功
        "400":
          description: バリデーションエラー

  /api/signup:
    post:
      tags:
        - authentication
      summary: ユーザー登録
      responses:
        "201":
          description: 登録成功
        "400":
          description: バリデーションエラー

  /api/setup-otp:
    get:
      tags:
        - otp
      summary: OTP初期設定情報取得
      security:
        - BearerAuth: []
      responses:
        "200":
          description: OTP設定情報
        "400":
          description: すでに設定済み

    post:
      tags:
        - otp
      summary: OTP設定の確定
      security:
        - BearerAuth: []
      responses:
        "200":
          description: 設定成功

  /api/verify-otp:
    post:
      tags:
        - otp
      summary: OTPトークン検証
      responses:
        "200":
          description: 検証成功
        "400":
          description: 検証失敗

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT