openapi: 3.0.0
info:
  title: Gameplay API
  description: API for ponglogic and gamesetting
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/SHAHRUKH4062_1/Gameplay/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://virtserver.swaggerhub.com/SHAHRUKH4062_1/Accounts/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://localhost:8443/
  description: ゲーム設定用APIサーバー
- url: wss://localhost:8443/
  description: WebSocketサーバー
paths:
  /gameplay/gamesetting/api/:
    post:
      tags:
      - setting
      summary: ゲーム設定を追加
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/gamesetting_api_body'
        required: true
      responses:
        "201":
          description: ゲーム設定が作成されました
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201'
        "400":
          description: リクエストのデータにエラーがあります
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_400'
  /gameplay/gamesetting/api/{id}/:
    delete:
      tags:
      - setting
      summary: ゲーム設定を削除
      parameters:
      - name: id
        in: path
        description: 削除するゲーム設定のID
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "204":
          description: ゲーム設定が削除されました
        "400":
          description: リクエストのデータにエラーがあります
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_400'
components:
  schemas:
    gamesetting_api_body:
      type: object
      properties:
        ball_velocity:
          type: string
          example: normal
        ball_size:
          type: string
          example: normal
        map:
          type: string
          example: A
    inline_response_201:
      type: object
      properties:
        id:
          type: integer
          example: 1
        ball_velocity:
          type: string
          example: normal
        ball_size:
          type: string
          example: normal
        map:
          type: string
          example: A
    inline_response_400:
      type: object
      properties:
        error:
          type: string
          example: 無効なリクエストデータ
