openapi: 3.0.0
info:
  title: 42 OAuth Authentication API
  description: API for 42 OAuth authentication flow
  version: 1.0.0
servers:
  - url: https://localhost:8443/42pong.api/account
    description: Production server
  - url: http://localhost:8000
    description: Development server

paths:
  /oauth:
    get:
      tags:
        - oauth
      summary: Initiate 42 OAuth authorization flow
      description: Redirects the user to 42's OAuth authorization page
      responses:
        '302':
          description: Redirect to 42's OAuth authorization page
          headers:
            Location:
              schema:
                type: string
                example: https://api.intra.42.fr/oauth/authorize?client_id={client_id}&redirect_uri={redirect_uri}&response_type=code

  /oauth/callback:
    get:
      tags:
        - oauth
      summary: Handle OAuth callback from 42
      description: Processes the authorization code and authenticates the user
      parameters:
        - name: code
          in: query
          description: Authorization code from 42
          schema:
            type: string
          required: false
        - name: error
          in: query
          description: Error message from 42
          schema:
            type: string
          required: false
        - name: error_description
          in: query
          description: Detailed error description
          schema:
            type: string
          required: false
      responses:
        '302':
          description: Successful authentication, redirect to frontend
          headers:
            Location:
              schema:
                type: string
                example: https://localhost:8443/#/
            Set-Cookie:
              schema:
                type: string
                example: token=dummy; Max-Age=86400; Secure; SameSite=Lax
        '400':
          description: Authentication failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: invalid_code
                  error_description:
                    type: string
                    example: Authorization code was not provided or is invalid.

components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://api.intra.42.fr/oauth/authorize
          tokenUrl: https://api.intra.42.fr/oauth/token
          scopes: {}
