# Generated by Django 5.1.4 on 2025-01-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="default_language",
            field=models.CharField(
                default="en",
                help_text="The user's preferred default language.",
                max_length=10,
            ),
        ),
    ]
