name: web-django-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13.0

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
      
      - name: Install Python dependencies
        run: |
          pip install -r web/requirements.txt

      - name: Run Django tests
        run: |
            cd web
            python3 manage.py test
